# Install script for directory: /home/opencv-4.x

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "1")
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

# Set default install directory permissions.
if(NOT DEFINED CMAKE_OBJDUMP)
  set(CMAKE_OBJDUMP "/usr/bin/objdump")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xlicensesx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/licenses/opencv4" TYPE FILE RENAME "opencl-headers-LICENSE.txt" FILES "/home/opencv-4.x/3rdparty/include/opencl/LICENSE.txt")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xlicensesx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/licenses/opencv4" TYPE FILE RENAME "ade-LICENSE" FILES "/home/build/3rdparty/ade/ade-0.1.2a/LICENSE")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xdevx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/opencv4/opencv2" TYPE FILE FILES "/home/build/cvconfig.h")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xdevx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/opencv4/opencv2" TYPE FILE FILES "/home/build/opencv2/opencv_modules.hpp")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xdevx" OR NOT CMAKE_INSTALL_COMPONENT)
  if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/cmake/opencv4/OpenCVModules.cmake")
    file(DIFFERENT EXPORT_FILE_CHANGED FILES
         "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/cmake/opencv4/OpenCVModules.cmake"
         "/home/build/CMakeFiles/Export/lib/cmake/opencv4/OpenCVModules.cmake")
    if(EXPORT_FILE_CHANGED)
      file(GLOB OLD_CONFIG_FILES "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/cmake/opencv4/OpenCVModules-*.cmake")
      if(OLD_CONFIG_FILES)
        message(STATUS "Old export file \"$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/cmake/opencv4/OpenCVModules.cmake\" will be replaced.  Removing files [${OLD_CONFIG_FILES}].")
        file(REMOVE ${OLD_CONFIG_FILES})
      endif()
    endif()
  endif()
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/opencv4" TYPE FILE FILES "/home/build/CMakeFiles/Export/lib/cmake/opencv4/OpenCVModules.cmake")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/opencv4" TYPE FILE FILES "/home/build/CMakeFiles/Export/lib/cmake/opencv4/OpenCVModules-release.cmake")
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xdevx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/opencv4" TYPE FILE FILES
    "/home/build/unix-install/OpenCVConfig-version.cmake"
    "/home/build/unix-install/OpenCVConfig.cmake"
    )
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xscriptsx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE FILE PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE FILES "/home/build/CMakeFiles/install/setup_vars_opencv4.sh")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xdevx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/opencv4" TYPE FILE FILES
    "/home/opencv-4.x/platforms/scripts/valgrind.supp"
    "/home/opencv-4.x/platforms/scripts/valgrind_3rdparty.supp"
    )
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/home/build/3rdparty/zlib/cmake_install.cmake")
  include("/home/build/3rdparty/libjpeg-turbo/cmake_install.cmake")
  include("/home/build/3rdparty/libtiff/cmake_install.cmake")
  include("/home/build/3rdparty/libwebp/cmake_install.cmake")
  include("/home/build/3rdparty/openjpeg/cmake_install.cmake")
  include("/home/build/3rdparty/libpng/cmake_install.cmake")
  include("/home/build/3rdparty/openexr/cmake_install.cmake")
  include("/home/build/3rdparty/protobuf/cmake_install.cmake")
  include("/home/build/3rdparty/quirc/cmake_install.cmake")
  include("/home/build/3rdparty/ittnotify/cmake_install.cmake")
  include("/home/build/include/cmake_install.cmake")
  include("/home/build/modules/.firstpass/calib3d/cmake_install.cmake")
  include("/home/build/modules/.firstpass/core/cmake_install.cmake")
  include("/home/build/modules/.firstpass/dnn/cmake_install.cmake")
  include("/home/build/modules/.firstpass/features2d/cmake_install.cmake")
  include("/home/build/modules/.firstpass/flann/cmake_install.cmake")
  include("/home/build/modules/.firstpass/gapi/cmake_install.cmake")
  include("/home/build/modules/.firstpass/highgui/cmake_install.cmake")
  include("/home/build/modules/.firstpass/imgcodecs/cmake_install.cmake")
  include("/home/build/modules/.firstpass/imgproc/cmake_install.cmake")
  include("/home/build/modules/.firstpass/java/cmake_install.cmake")
  include("/home/build/modules/.firstpass/js/cmake_install.cmake")
  include("/home/build/modules/.firstpass/ml/cmake_install.cmake")
  include("/home/build/modules/.firstpass/objc/cmake_install.cmake")
  include("/home/build/modules/.firstpass/objdetect/cmake_install.cmake")
  include("/home/build/modules/.firstpass/photo/cmake_install.cmake")
  include("/home/build/modules/.firstpass/python/cmake_install.cmake")
  include("/home/build/modules/.firstpass/stitching/cmake_install.cmake")
  include("/home/build/modules/.firstpass/ts/cmake_install.cmake")
  include("/home/build/modules/.firstpass/video/cmake_install.cmake")
  include("/home/build/modules/.firstpass/videoio/cmake_install.cmake")
  include("/home/build/modules/.firstpass/world/cmake_install.cmake")
  include("/home/build/modules/.firstpass/alphamat/cmake_install.cmake")
  include("/home/build/modules/.firstpass/aruco/cmake_install.cmake")
  include("/home/build/modules/.firstpass/barcode/cmake_install.cmake")
  include("/home/build/modules/.firstpass/bgsegm/cmake_install.cmake")
  include("/home/build/modules/.firstpass/bioinspired/cmake_install.cmake")
  include("/home/build/modules/.firstpass/ccalib/cmake_install.cmake")
  include("/home/build/modules/.firstpass/cnn_3dobj/cmake_install.cmake")
  include("/home/build/modules/.firstpass/cudaarithm/cmake_install.cmake")
  include("/home/build/modules/.firstpass/cudabgsegm/cmake_install.cmake")
  include("/home/build/modules/.firstpass/cudacodec/cmake_install.cmake")
  include("/home/build/modules/.firstpass/cudafeatures2d/cmake_install.cmake")
  include("/home/build/modules/.firstpass/cudafilters/cmake_install.cmake")
  include("/home/build/modules/.firstpass/cudaimgproc/cmake_install.cmake")
  include("/home/build/modules/.firstpass/cudalegacy/cmake_install.cmake")
  include("/home/build/modules/.firstpass/cudaobjdetect/cmake_install.cmake")
  include("/home/build/modules/.firstpass/cudaoptflow/cmake_install.cmake")
  include("/home/build/modules/.firstpass/cudastereo/cmake_install.cmake")
  include("/home/build/modules/.firstpass/cudawarping/cmake_install.cmake")
  include("/home/build/modules/.firstpass/cudev/cmake_install.cmake")
  include("/home/build/modules/.firstpass/cvv/cmake_install.cmake")
  include("/home/build/modules/.firstpass/datasets/cmake_install.cmake")
  include("/home/build/modules/.firstpass/dnn_objdetect/cmake_install.cmake")
  include("/home/build/modules/.firstpass/dnn_superres/cmake_install.cmake")
  include("/home/build/modules/.firstpass/dpm/cmake_install.cmake")
  include("/home/build/modules/.firstpass/face/cmake_install.cmake")
  include("/home/build/modules/.firstpass/freetype/cmake_install.cmake")
  include("/home/build/modules/.firstpass/fuzzy/cmake_install.cmake")
  include("/home/build/modules/.firstpass/hdf/cmake_install.cmake")
  include("/home/build/modules/.firstpass/hfs/cmake_install.cmake")
  include("/home/build/modules/.firstpass/img_hash/cmake_install.cmake")
  include("/home/build/modules/.firstpass/intensity_transform/cmake_install.cmake")
  include("/home/build/modules/.firstpass/julia/cmake_install.cmake")
  include("/home/build/modules/.firstpass/line_descriptor/cmake_install.cmake")
  include("/home/build/modules/.firstpass/matlab/cmake_install.cmake")
  include("/home/build/modules/.firstpass/mcc/cmake_install.cmake")
  include("/home/build/modules/.firstpass/optflow/cmake_install.cmake")
  include("/home/build/modules/.firstpass/ovis/cmake_install.cmake")
  include("/home/build/modules/.firstpass/phase_unwrapping/cmake_install.cmake")
  include("/home/build/modules/.firstpass/plot/cmake_install.cmake")
  include("/home/build/modules/.firstpass/quality/cmake_install.cmake")
  include("/home/build/modules/.firstpass/rapid/cmake_install.cmake")
  include("/home/build/modules/.firstpass/reg/cmake_install.cmake")
  include("/home/build/modules/.firstpass/rgbd/cmake_install.cmake")
  include("/home/build/modules/.firstpass/saliency/cmake_install.cmake")
  include("/home/build/modules/.firstpass/sfm/cmake_install.cmake")
  include("/home/build/modules/.firstpass/shape/cmake_install.cmake")
  include("/home/build/modules/.firstpass/stereo/cmake_install.cmake")
  include("/home/build/modules/.firstpass/structured_light/cmake_install.cmake")
  include("/home/build/modules/.firstpass/superres/cmake_install.cmake")
  include("/home/build/modules/.firstpass/surface_matching/cmake_install.cmake")
  include("/home/build/modules/.firstpass/text/cmake_install.cmake")
  include("/home/build/modules/.firstpass/tracking/cmake_install.cmake")
  include("/home/build/modules/.firstpass/videostab/cmake_install.cmake")
  include("/home/build/modules/.firstpass/viz/cmake_install.cmake")
  include("/home/build/modules/.firstpass/wechat_qrcode/cmake_install.cmake")
  include("/home/build/modules/.firstpass/xfeatures2d/cmake_install.cmake")
  include("/home/build/modules/.firstpass/ximgproc/cmake_install.cmake")
  include("/home/build/modules/.firstpass/xobjdetect/cmake_install.cmake")
  include("/home/build/modules/.firstpass/xphoto/cmake_install.cmake")
  include("/home/build/modules/core/cmake_install.cmake")
  include("/home/build/modules/flann/cmake_install.cmake")
  include("/home/build/modules/imgproc/cmake_install.cmake")
  include("/home/build/modules/ml/cmake_install.cmake")
  include("/home/build/modules/plot/cmake_install.cmake")
  include("/home/build/modules/features2d/cmake_install.cmake")
  include("/home/build/modules/imgcodecs/cmake_install.cmake")
  include("/home/build/modules/videoio/cmake_install.cmake")
  include("/home/build/modules/calib3d/cmake_install.cmake")
  include("/home/build/modules/highgui/cmake_install.cmake")
  include("/home/build/modules/video/cmake_install.cmake")
  include("/home/build/modules/xfeatures2d/cmake_install.cmake")
  include("/home/build/modules/tracking/cmake_install.cmake")
  include("/home/build/doc/cmake_install.cmake")
  include("/home/build/data/cmake_install.cmake")
  include("/home/build/apps/cmake_install.cmake")

endif()

if(CMAKE_INSTALL_COMPONENT)
  set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
else()
  set(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
file(WRITE "/home/build/${CMAKE_INSTALL_MANIFEST}"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
